title: Liam Bessell
description: Hello and welcome to my portfolio! I am a Junior computer science major aspiring to become a software developer.This page features a collection of small independent projects I've worked on recently.

I can be reached at lbessell@tamu.edu if you have any questions, comments, or just want to say hello!
theme: jekyll-theme-minimal
