name: Goodreads Scrape Scheduler
on:
  schedule:
    - cron: "0 * * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Install BeautifulSoup
        run: pip install BeautifulSoup
      - name: Run scraper
        run: python goodreads-scraper.py
      - uses: stefanzweifel/git-auto-commit-action@v4     # Todo: Change this