name: Goodreads Scrape Scheduler
on:
  schedule:
    - cron: '0 0 * * *'
    #branches:
      #- 'master'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Install BeautifulSoup
        run: pip install beautifulsoup4

      - name: Run scraper
        run: python goodreads-scraper.py

      - name: Commit and push
        uses: devops-infra/action-commit-push@master
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          commit_prefix: "[AUTO]"
          commit_message: "Automatic commit"
          force: false
      
      #- name: Build and deploy hugo
